spring.application.name=expensemanager

spring.datasource.url=jdbc:postgresql://localhost:5432/expensedb
spring.datasource.username=postgres
spring.datasource.password=@rahuL885131
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.jpa.show-sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379



logging.level.org.springframework.security=DEBUG
server.error.include-message=always
server.error.include-stacktrace=always


jwt.secret: 0c0e154ae828b17e90a8c9f57ce102ae9de21fb06623eec6441c2619ade122c5
jwt.expirationMs: 86400000



